version: '3.7'

networks:
  internal:
    name: djpgp-network

volumes:
  database_data:
    name: djpgp-database_data

services:

  #-----------------------------------#
  #             Database              #
  #-----------------------------------#
  database:
    image: postgis/postgis:12-3.0-alpine
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DJPGP_PGPASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 3s
      retries: 5
    restart: on-failure
    env_file: .env
    networks:
      - internal
    ports:
      - 9876:5432
