# Generated by Django 3.0.8 on 2020-08-13 16:02

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('vacancies_url', models.URLField(verbose_name='Vacancies Url')),
                ('last_updated', models.DateField(verbose_name='Last Updated')),
                ('update_freq', models.IntegerField(default=0, verbose_name='Update Frequency (in days)')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=50, verbose_name='Role Title')),
                ('description', models.TextField()),
                ('url', models.URLField(verbose_name='Job Url')),
                ('is_remote', models.NullBooleanField(verbose_name='Is Remote')),
                ('part_time_permitted', models.NullBooleanField(verbose_name='Part-Time Permitted')),
                ('has_401k', models.NullBooleanField(verbose_name='Has 401k')),
                ('has_dentalins', models.NullBooleanField(verbose_name='Has Dental Insurance')),
                ('has_healthins', models.NullBooleanField(verbose_name='Has Health Insurance')),
                ('salary_range', django.contrib.postgres.fields.ranges.IntegerRangeField(verbose_name='Salary Range')),
                ('date_active', models.DateField(verbose_name='Date Active')),
                ('date_inactive', models.DateField(verbose_name='Date Inactive')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='GPS Coord')),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Opening')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
