# Generated by Django 3.0.8 on 2020-08-15 14:54

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='date_inactive',
            field=models.DateField(blank=True, null=True, verbose_name='Date Inactive'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='role_title',
            field=models.CharField(max_length=100, verbose_name='Role Title'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='salary_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='Salary Range'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='url',
            field=models.URLField(unique=True, verbose_name='Job Url'),
        ),
    ]
