# Generated by Django 3.0.8 on 2020-08-16 13:54

from django.db import migrations, models
import django.utils.timezone
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200815_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_updated',
            field=models.DateTimeField(verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Name Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='update_freq',
            field=models.IntegerField(default=0, verbose_name='Update Frequency'),
        ),
        migrations.AddField(
            model_name='opening',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='last_processed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Processed'),
        ),
    ]
