# Generated by Django 3.0.8 on 2020-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200816_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='opening',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='opening',
            name='locations',
            field=models.ManyToManyField(blank=True, to='jobs.Location'),
        ),
    ]
